FROM tomcat:9.0-jdk17

RUN rm -rf /usr/local/tomcat/webapps/*

# Copia tu WAR y lo pone como ROOT.war (para que abra en "/")
COPY app.war /usr/local/tomcat/webapps/StreamingApp.war

EXPOSE 8080

CMD ["catalina.sh", "run"]
